---
deployment:
  tasks:
    - export DEPLOYPATH=/home/haydi/haydihepberaber/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH 2>/dev/null || :
    - cd $DEPLOYPATH
    - if [ -f package.json ]; then npm install --production --prefer-offline; fi
