---
deployment:
  tasks:
    - export DEPLOYPATH=/home/haydi/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH 2>/dev/null || :
    - cd $DEPLOYPATH
    - npm install --production
